import { checkSchema } from 'express-validator'
import { HttpStatus } from '~/constants/httpStatus'
import { PROPERTY_MESSAGES } from '~/constants/message'
import { ErrorWithStatus } from '~/models/Errors'
import { databaseService } from '~/services/database.service'
import { validate } from '~/utils/validation'
